# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='alternateContact',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='fatherName',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='motherName',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='nativePlace',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
    ]
